// AUTOGENERATED by scripts/embed-web.ts — do not edit.
// Stub: populated at compile time so the binary embeds packages/web/dist.
// In dev (bun run ra), this stays empty and the web server falls back to
// reading packages/web/dist from disk.

export const embeddedWebAssets: Record<string, string> = {}
