#!/usr/bin/env bun
// Scans packages/web/dist and writes src/web/embedded-assets.generated.ts
// with static `import … with { type: 'file' }` lines so `bun build --compile`
// embeds every web asset into the standalone binary.

import { readdirSync, statSync } from 'fs'
import { join, relative, posix, sep } from 'path'

const APP_ROOT = join(import.meta.dir, '..')
const WEB_DIST = join(APP_ROOT, '../web/dist')
const OUT_FILE = join(APP_ROOT, 'src/web/embedded-assets.generated.ts')

function walk(dir: string, acc: string[] = []): string[] {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry)
    if (statSync(full).isDirectory()) walk(full, acc)
    else acc.push(full)
  }
  return acc
}

function toVar(i: number): string {
  return `f${i}`
}

function main(): void {
  let files: string[] = []
  try {
    files = walk(WEB_DIST).sort()
  } catch {
    console.error(`[embed-web] ${WEB_DIST} not found — run 'bun run build' in packages/web first`)
    process.exit(1)
  }

  if (files.length === 0) {
    console.error(`[embed-web] ${WEB_DIST} is empty`)
    process.exit(1)
  }

  const imports: string[] = []
  const entries: string[] = []
  files.forEach((abs, i) => {
    const rel = relative(join(APP_ROOT, 'src/web'), abs).split(sep).join(posix.sep)
    const url = '/' + relative(WEB_DIST, abs).split(sep).join(posix.sep)
    const v = toVar(i)
    imports.push(`import ${v} from '${rel}' with { type: 'file' }`)
    entries.push(`  '${url}': ${v},`)
  })

  const body = [
    '// AUTOGENERATED by scripts/embed-web.ts — do not edit.',
    '// Each import becomes an embedded file in the compiled binary.',
    '',
    ...imports,
    '',
    'export const embeddedWebAssets: Record<string, string> = {',
    ...entries,
    '}',
    '',
  ].join('\n')

  Bun.write(OUT_FILE, body)
  console.error(`[embed-web] wrote ${files.length} entries → ${relative(APP_ROOT, OUT_FILE)}`)
}

main()
