export { discoverContextFiles, discoverContextInDirs, findGitRoot } from './discovery'
export { buildContextMessages } from './inject'
export { resolvePatterns, formatResolvedReferences } from './resolvers'
export { createResolverMiddleware } from './resolve-middleware'
export { createDiscoveryMiddleware } from './discovery-middleware'
export { builtinResolvers } from './builtin-resolvers'
export type { ContextConfig, ContextFile, ResolverConfig } from './types'
export type { DiscoverOptions } from './discovery'
export type { DiscoveryMiddlewareOptions } from './discovery-middleware'
export type { PatternResolver, ResolvedReference, ResolutionResult } from './resolvers'
